import {
  WebsiteSettings,
  DiscordSettings,
  HomepageConfig,
  HostingPlan,
  PlanCategory,
  FeatureItem,
  FaqItem,
  ReviewItem,
  Announcement,
  SocialLinks,
  AdminRoleDefinition
} from '../types';

export const ALL_PERMISSIONS = [
  'View Dashboard',
  'Manage Website',
  'Manage Homepage',
  'Manage Plans',
  'Manage Categories',
  'Manage Users',
  'Manage Admins',
  'Manage Roles',
  'Manage FAQ',
  'Manage Reviews',
  'Manage Announcements',
  'Manage Notifications',
  'Manage Support',
  'View Logs',
  'View Audit Logs',
  'Manage Discord Settings',
] as const;

export const DEFAULT_ROLES: AdminRoleDefinition[] = [
  {
    id: 'owner',
    name: 'Owner',
    description: 'Full root access to all website configurations, admin roles, and financial records.',
    permissions: [...ALL_PERMISSIONS],
    isSystem: true,
  },
  {
    id: 'super-admin',
    name: 'Super Admin',
    description: 'Elevated management across all CMS, plans, users, and audit logs.',
    permissions: [
      'View Dashboard',
      'Manage Website',
      'Manage Homepage',
      'Manage Plans',
      'Manage Categories',
      'Manage Users',
      'Manage Roles',
      'Manage FAQ',
      'Manage Reviews',
      'Manage Announcements',
      'Manage Notifications',
      'Manage Support',
      'View Logs',
      'View Audit Logs',
      'Manage Discord Settings',
    ],
    isSystem: true,
  },
  {
    id: 'admin',
    name: 'Admin',
    description: 'Standard administrative control over hosting plans, categories, content, and inquiries.',
    permissions: [
      'View Dashboard',
      'Manage Website',
      'Manage Homepage',
      'Manage Plans',
      'Manage Categories',
      'Manage Users',
      'Manage FAQ',
      'Manage Reviews',
      'Manage Announcements',
      'Manage Notifications',
      'Manage Support',
      'View Logs',
      'Manage Discord Settings',
    ],
    isSystem: true,
  },
  {
    id: 'moderator',
    name: 'Moderator',
    description: 'Community moderation, user support inquiries, FAQ updates, and review approvals.',
    permissions: [
      'View Dashboard',
      'Manage FAQ',
      'Manage Reviews',
      'Manage Announcements',
      'Manage Support',
      'View Logs',
    ],
    isSystem: true,
  },
  {
    id: 'support',
    name: 'Support',
    description: 'Customer inquiry support and user plan inquiries viewer.',
    permissions: [
      'View Dashboard',
      'Manage Support',
      'View Logs',
    ],
    isSystem: true,
  },
];

export const INITIAL_WEBSITE_SETTINGS: WebsiteSettings = {
  websiteName: 'Eclipse Cloud',
  logoText: 'Eclipse Cloud',
  logoUrl: '',
  faviconUrl: '',
  description: 'Enterprise-grade, ultra low-latency Minecraft server hosting powered by Ryzen 9 7950X CPUs, NVMe Gen4 SSDs, and 2.5+ Tbps Path.net DDoS protection.',
  browserTitle: 'Eclipse Cloud | Premium High-Performance Minecraft Hosting',
  seoDescription: 'Order high performance Minecraft server hosting with instant Discord-guided onboarding, 99.99% uptime, and dedicated hardware.',
  footerText: 'Eclipse Cloud provides ultra-low latency game server infrastructure with 24/7 dedicated support via Discord. Not an official Minecraft product. Not approved by or associated with Mojang or Microsoft.',
  copyrightText: '© 2026 Eclipse Cloud Networks LLC. All rights reserved.',
  serverNodeCount: '14+ Global Locations',
  uptimeGuarantee: '99.99% SLA Uptime',
  activePlayersEstimate: '45,000+ Online Players',
  supportEmail: 'support@eclipsecloud.com',
};

export const INITIAL_DISCORD_SETTINGS: DiscordSettings = {
  mainInviteUrl: 'https://discord.gg/minecraft',
  supportInviteUrl: 'https://discord.gg/minecraft',
  orderInviteUrl: 'https://discord.gg/minecraft',
  buttonText: 'Join Discord Server',
  serverName: 'Eclipse Cloud Official Discord',
  iconUrl: '',
  description: 'Our Discord server is the central hub for inquiries, custom server orders, modpack requests, and 24/7 priority support tickets.',
  memberCountEstimate: '18,400+ Discord Members',
};

export const INITIAL_HOMEPAGE_CONFIG: HomepageConfig = {
  heroHeading: 'Ultra-Fast Minecraft Server Hosting',
  heroSubheading: 'Powered by AMD Ryzen 9 7950X & Enterprise DDR5 Memory',
  heroDescription: 'Experience zero lag, instant Discord-coordinated order fulfillment, and military-grade 2.5+ Tbps DDoS defense. Scale your community from vanilla SMP to massive 500-player networks.',
  heroCtaText: 'View Server Plans',
  heroCtaLink: '#plans',
  heroDiscordText: 'Order on Discord',
  heroBackgroundUrl: '',
  heroVisible: true,
  whyChooseUsTitle: 'Engineered for Performance & Zero Bottlenecks',
  whyChooseUsDescription: 'We invest exclusively in top-tier dedicated hardware so your players enjoy silky smooth 20 TPS with heavy modpacks and high view distances.',
  featuresTitle: 'Next-Generation Infrastructure',
  featuresSubtitle: 'Everything you need to run a flawless Minecraft community without server lag or downtime.',
  faqTitle: 'Frequently Asked Questions',
  faqSubtitle: 'Everything you need to know about our plans, Discord ordering process, and hardware.',
  reviewsTitle: 'Trusted by Server Owners Worldwide',
  reviewsSubtitle: 'See why Minecraft communities, SMP creators, and network owners trust our hosting platform.',
  ctaBannerHeading: 'Ready to Launch Your Dream Minecraft Server?',
  ctaBannerText: 'Select your preferred hardware plan and our Discord deployment team will assist your setup in minutes.',
  ctaBannerButtonText: 'Explore Plans & Order',
};

export const INITIAL_CATEGORIES: PlanCategory[] = [
  {
    id: 'budget',
    name: 'Budget Tier',
    slug: 'budget',
    description: 'Perfect for vanilla SMPs, friend groups, and small survival worlds.',
    icon: 'Shield',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'premium',
    name: 'Performance Tier',
    slug: 'premium',
    description: 'Optimized for Paper, Purpur, Spigot with plugins and medium player counts.',
    icon: 'Zap',
    displayOrder: 2,
    active: true,
  },
  {
    id: 'extreme',
    name: 'Extreme / Modded',
    slug: 'extreme',
    description: 'Heavy modpacks (All The Mods, RLcraft, Forge, Fabric) and high tick rates.',
    icon: 'Flame',
    displayOrder: 3,
    active: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise & Networks',
    slug: 'enterprise',
    description: 'Velocity/BungeeCord proxy networks, mini-game hubs, and 200+ concurrent players.',
    icon: 'Crown',
    displayOrder: 4,
    active: true,
  },
];

export const INITIAL_PLANS: HostingPlan[] = [
  {
    id: 'stone-plan',
    name: 'Stone Plan',
    category: 'Budget Tier',
    price: 3.99,
    currency: '$',
    billingPeriod: '/mo',
    ram: '3 GB DDR5',
    cpu: '150% Ryzen 9',
    storage: '35 GB NVMe SSD',
    description: 'Ideal starting node for small private friend SMPs and vanilla adventures up to 10 players.',
    features: [
      '3 GB DDR5 5600MHz RAM',
      '1.5 vCPU Ryzen 9 7950X',
      '35 GB Gen4 NVMe Storage',
      'Unmetered Bandwidth',
      '2.5 Tbps Path.net DDoS Shield',
      'Free Custom Subdomain (you.novacraft.me)',
      'Discord Ticket Order Onboarding',
    ],
    badge: 'Starter Choice',
    icon: 'Box',
    isPopular: false,
    isBestValue: false,
    displayOrder: 1,
    active: true,
    discordCtaText: 'Order on Discord',
  },
  {
    id: 'iron-plan',
    name: 'Iron Plan',
    category: 'Budget Tier',
    price: 6.99,
    currency: '$',
    billingPeriod: '/mo',
    ram: '6 GB DDR5',
    cpu: '200% Ryzen 9',
    storage: '60 GB NVMe SSD',
    description: 'Great for active vanilla or lightweight Paper server with essential protection plugins.',
    features: [
      '6 GB DDR5 5600MHz RAM',
      '2 vCPUs Ryzen 9 7950X',
      '60 GB Gen4 NVMe Storage',
      'Unmetered Bandwidth',
      '2.5 Tbps Path.net DDoS Shield',
      'Free Custom Subdomain',
      'Discord Priority Order Assist',
    ],
    badge: 'Popular Budget',
    icon: 'Layers',
    isPopular: false,
    isBestValue: false,
    displayOrder: 2,
    active: true,
    discordCtaText: 'Order on Discord',
  },
  {
    id: 'redstone-plan',
    name: 'Redstone Pro',
    category: 'Performance Tier',
    price: 11.99,
    currency: '$',
    billingPeriod: '/mo',
    ram: '10 GB DDR5',
    cpu: '300% Ryzen 9',
    storage: '100 GB NVMe SSD',
    description: 'The golden standard for growing community SMPs, Towny, Lifesteal, and 30+ players.',
    features: [
      '10 GB DDR5 5600MHz RAM',
      '3 vCPUs Ryzen 9 7950X @ 5.7GHz',
      '100 GB Gen4 NVMe SSD',
      'Ultra Low Latency Global Nodes',
      'Real-Time DDoS Filtering',
      'Free Dedicated Port & Subdomain',
      'Fast Discord Order Provisioning',
    ],
    badge: 'MOST POPULAR',
    icon: 'Zap',
    isPopular: true,
    isBestValue: false,
    displayOrder: 3,
    active: true,
    discordCtaText: 'Order on Discord',
  },
  {
    id: 'diamond-plan',
    name: 'Diamond Heavy',
    category: 'Extreme / Modded',
    price: 18.99,
    currency: '$',
    billingPeriod: '/mo',
    ram: '16 GB DDR5',
    cpu: '400% Ryzen 9',
    storage: '160 GB NVMe SSD',
    description: 'Built for heavy Forge, Fabric, and NeoForge modpacks with 250+ mods and world generation.',
    features: [
      '16 GB DDR5 ECC RAM',
      '4 Dedicated Ryzen vCPUs',
      '160 GB Gen4 NVMe Storage',
      'Automatic Daily Offsite Backups',
      'Path.net Game-Specific Mitigation',
      'Dedicated IP Included',
      'VIP Discord White-Glove Support',
    ],
    badge: 'BEST VALUE',
    icon: 'Gem',
    isPopular: false,
    isBestValue: true,
    displayOrder: 4,
    active: true,
    discordCtaText: 'Order on Discord',
  },
  {
    id: 'netherite-plan',
    name: 'Netherite Extreme',
    category: 'Extreme / Modded',
    price: 27.99,
    currency: '$',
    billingPeriod: '/mo',
    ram: '24 GB DDR5',
    cpu: '500% Ryzen 9',
    storage: '250 GB NVMe SSD',
    description: 'Maximum power for large public SMP servers, high view distances (16+ chunks), and constant 20 TPS.',
    features: [
      '24 GB DDR5 Ultra-Speed RAM',
      '5 Dedicated Ryzen vCPUs',
      '250 GB Enterprise NVMe',
      'Priority VIP Routing & Anycast',
      'Custom Reverse Proxy Ready',
      'Dedicated IP & Custom Port',
      'Direct Discord Staff Channel',
    ],
    badge: 'Maximum Modded',
    icon: 'Flame',
    isPopular: false,
    isBestValue: false,
    displayOrder: 5,
    active: true,
    discordCtaText: 'Order on Discord',
  },
  {
    id: 'dragon-plan',
    name: 'Ender Dragon Dedicated Node',
    category: 'Enterprise & Networks',
    price: 49.99,
    currency: '$',
    billingPeriod: '/mo',
    ram: '48 GB DDR5',
    cpu: '8 Dedicated Threads',
    storage: '500 GB NVMe SSD',
    description: 'Full network proxy infrastructure designed for multi-server setups (Hub, Survival, Skyblock, Minigames).',
    features: [
      '48 GB Enterprise DDR5 RAM',
      '8 High-Clock Ryzen 9 Threads',
      '500 GB Samsung 990 Pro NVMe',
      'Custom Anycast BGP Routing',
      'Multi-Server Cross Link Setup Assist',
      'Guaranteed 99.99% Hardware SLA',
      'Private Senior Tech Discord Channel',
    ],
    badge: 'Enterprise Giant',
    icon: 'Crown',
    isPopular: false,
    isBestValue: false,
    displayOrder: 6,
    active: true,
    discordCtaText: 'Order on Discord',
  },
];

export const INITIAL_FEATURES: FeatureItem[] = [
  {
    id: 'feat-cpu',
    title: 'AMD Ryzen 9 7950X / 9950X',
    description: 'Clocked up to 5.7 GHz single-core speeds to conquer single-threaded Minecraft server world generation without tick drops.',
    icon: 'Cpu',
    displayOrder: 1,
    active: true,
    badge: '5.7 GHz Turbo',
  },
  {
    id: 'feat-ddos',
    title: '2.5+ Tbps DDoS Mitigation',
    description: 'Enterprise Path.net and CosmicGuard protection with custom Minecraft layer 7 packet filtering to stop botnets cold.',
    icon: 'ShieldCheck',
    displayOrder: 2,
    active: true,
    badge: 'Always Active',
  },
  {
    id: 'feat-nvme',
    title: 'PCIe Gen4 NVMe Storage',
    description: 'Ultra-fast 7,000MB/s read and write speeds. Chunks render instantaneously with zero disk I/O stuttering.',
    icon: 'HardDrive',
    displayOrder: 3,
    active: true,
  },
  {
    id: 'feat-ram',
    title: 'DDR5 5600MHz High-Speed RAM',
    description: 'Equipped with next-gen error-correcting high-bandwidth DDR5 memory preventing memory crashes.',
    icon: 'Server',
    displayOrder: 4,
    active: true,
  },
  {
    id: 'feat-discord',
    title: 'Instant Discord Onboarding',
    description: 'Direct human assistance in our active Discord community to help you choose the ideal plan and guide configuration.',
    icon: 'MessageSquare',
    displayOrder: 5,
    active: true,
  },
  {
    id: 'feat-uptime',
    title: '99.99% Uptime Guarantee',
    description: 'Redundant power arrays, dual tier-1 network carriers, and automated failover monitoring 24 hours a day, 365 days a year.',
    icon: 'Activity',
    displayOrder: 6,
    active: true,
  },
];

export const INITIAL_FAQS: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'How does ordering a Minecraft hosting plan work?',
    answer: 'We operate an exclusive, high-touch Discord-based ordering system. When you click "Buy Plan" or "Order Now", you will be guided to our Official Discord server. In the #order-support channel, you can open a quick ticket where our staff confirms your desired plan, location, and setup details directly without automated surprises.',
    category: 'Orders',
    displayOrder: 1,
    active: true,
  },
  {
    id: 'faq-2',
    question: 'Why do you use Discord for ordering instead of instant payment gateway?',
    answer: 'Community owners love transparency and tailored support. By coordinating through Discord, our team verifies that the chosen RAM and CPU allocation match your exact player count and modpack requirements before anything is finalized, ensuring you never overpay or suffer under-allocated RAM.',
    category: 'Orders',
    displayOrder: 2,
    active: true,
  },
  {
    id: 'faq-3',
    question: 'Are heavy modpacks (Forge, Fabric, All The Mods) supported?',
    answer: 'Yes! Our Performance and Extreme tiers (Diamond, Netherite, Ender Dragon) are specifically architected for resource-intensive modpacks like ATM 9, Better MC, RLcraft, and Cobblemon.',
    category: 'Hardware',
    displayOrder: 3,
    active: true,
  },
  {
    id: 'faq-4',
    question: 'Can I upgrade my RAM or CPU tier later?',
    answer: 'Absolutely. You can request a seamless plan upgrade at any time through our Discord ticket system with zero data loss.',
    category: 'Billing',
    displayOrder: 4,
    active: true,
  },
  {
    id: 'faq-5',
    question: 'What kind of DDoS protection do you provide?',
    answer: 'All plans include permanent 2.5+ Tbps inline DDoS mitigation powered by Path.net. It inspects Minecraft handshake packets and filters OVH/Hetzner reflection attacks, UDP floods, and SYN floods with zero added latency.',
    category: 'Security',
    displayOrder: 5,
    active: true,
  },
  {
    id: 'faq-6',
    question: 'Do I get a free subdomain or dedicated IP?',
    answer: 'Yes! Every server receives a free custom subdomain (such as yourname.novacraft.me). Plans with 16GB RAM and above include a dedicated IPv4 address at standard port 25565.',
    category: 'Network',
    displayOrder: 6,
    active: true,
  },
];

export const INITIAL_REVIEWS: ReviewItem[] = [
  {
    id: 'rev-1',
    authorName: 'Alex_Crafter99',
    authorRole: 'Owner of Aetheria SMP (85+ active players)',
    rating: 5,
    reviewText: 'Moved our 80-player community from another host where TPS was dropping to 14 during peak hours. On NovaCraft Netherite plan with Ryzen 9, we stay locked at a solid 20.0 TPS even with 25 players at mob farms simultaneously!',
    verified: true,
    active: true,
    displayOrder: 1,
  },
  {
    id: 'rev-2',
    authorName: 'VortexAdmin',
    authorRole: 'Lead Dev at PixelBlock Network',
    rating: 5,
    reviewText: 'The Discord ordering and support flow is incredible. Instead of robotic automated emails, a real staff member hopped on our ticket in under 2 minutes, helped configure our Velocity proxy, and had us live.',
    verified: true,
    active: true,
    displayOrder: 2,
  },
  {
    id: 'rev-3',
    authorName: 'SarahM_MC',
    authorRole: 'Creator & Streamer',
    rating: 5,
    reviewText: 'Running an ATM9 modded server with 300+ mods used to be a nightmare with memory leaks. The Diamond 16GB DDR5 plan handles dimensional travel and quarry mining effortlessly.',
    verified: true,
    active: true,
    displayOrder: 3,
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: '⚡ Spring Hosting Special',
    text: 'Join our Discord today and mention code "NOVACRAFT20" in your order ticket for 20% off all Netherite and Dragon plans!',
    ctaText: 'Claim on Discord',
    ctaLink: 'https://discord.gg/minecraft',
    type: 'success',
    active: true,
    createdDate: new Date().toISOString(),
  },
];

export const INITIAL_SOCIAL_LINKS: SocialLinks = {
  discord: 'https://discord.gg/minecraft',
  twitter: 'https://twitter.com/novacrafthosting',
  youtube: 'https://youtube.com',
  github: 'https://github.com',
  tiktok: 'https://tiktok.com',
  instagram: 'https://instagram.com',
};
